
services:
  flask-api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: flask-api
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
