services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: keycloak
    # Usuário e senha do Admin Keycloak (para acessar o console)
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Banco de dados de desenvolvimento (H2 em memória). Em produção, use algo persistente.
      KC_DB: dev-mem
    # Montamos o arquivo labrealm.json no caminho padrão de import do Keycloak
    volumes:
      - ./labrealm.json:/opt/keycloak/data/import/labrealm.json
    # Ao iniciar, usamos 'start-dev' e passamos '--import-realm'
    command: >
      start-dev --import-realm
    ports:
      - "8080:8080"
  
  # Exemplo de outro serviço: a aplicação Flask
  lab03_flask_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: lab03_flask_app
    # (outras configs, variáveis de ambiente, etc.)
    ports:
      - "5000:5000"
    depends_on:
      - keycloak
