services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
      # Dica: existem várias formas de configurar o Keycloak; esse exemplo usa H2 em memória
    ports:
      - "8080:8080"
    command: >
      start-dev --hostname-strict=false 
        --http-relative-path=/
    # 'start-dev' é para ambientes de desenvolvimento

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab03_flask_app
    environment:
      KEYCLOAK_ISSUER_URL: http://keycloak:8080/realms/jwt-realm
      KEYCLOAK_CLIENT_ID: lab03-client
      # etc.
    ports:
      - "5000:5000"
    depends_on:
      - keycloak